<div class="container">

    <div class="principal">
        <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/895/331/themes/new_linkedman/1-slide-1649101698786-3479607614-682f3c987af787b93925c87cc9d675d21649101730-1920-1920.webp?568932035" alt="">
        <div class="servico-container">
        <div class="servico">
            <h3>
                Site Seguro
            </h3>
            <p>Compre com segurança e confiança!</p>
        </div>
        <div class="servico">
            <h3>
                COMPRE E RETIRE NO MESMO DIA
            </h3>
        </div>
        <div class="servico">
            <h3>
                PARCELAMENTO EM ATÉ 3X
            </h3>
            <p>Sem juros!</p>
        </div>
        </div>
    </div>

    <div class="conteudo">

        <div class="classe-produto">
            <h2>
                Princiais Masculino
            </h2>
            <div class="produtos">
                <div class="produto">
                    <div class="img-produtos">
                        <a href="">
                            <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/895/331/products/tshirt-silk-telha-frente-014031-abba04dec7e7c0aab016454580004355-320-0.jpg" alt="">
                        </a>
                    </div>
                    <div class="descricao-produtos">
                        <a href="">
                            <h5>T-SHIRT BICICLETA</h5>
                        </a>
                        <p>R$69,90</p>
                        <p>3X DE R$23,30 SEM JUROS</p>
                    </div>
                </div>

                <div class="produto">
                    <div class="img-produtos">
                        <a href="">
                            <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/895/331/products/tshirt-silk-telha-frente-014031-abba04dec7e7c0aab016454580004355-320-0.jpg" alt="">
                        </a>
                    </div>
                    <div class="descricao-produtos">
                        <a href="">
                            <h5>T-SHIRT BICICLETA</h5>
                        </a>
                        <p>R$69,90</p>
                        <p>3X DE R$23,30 SEM JUROS</p>
                    </div>
                </div>

                <div class="produto">
                    <div class="img-produtos">
                        <a href="">
                            <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/895/331/products/tshirt-silk-telha-frente-014031-abba04dec7e7c0aab016454580004355-320-0.jpg" alt="">
                        </a>
                    </div>
                    <div class="descricao-produtos">
                        <a href="">
                            <h5>T-SHIRT BICICLETA</h5>
                        </a>
                        <p>R$69,90</p>
                        <p>3X DE R$23,30 SEM JUROS</p>
                    </div>
                </div>
                
                <div class="produto">
                    <div class="img-produtos">
                        <a href="">
                            <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/895/331/products/tshirt-silk-telha-frente-014031-abba04dec7e7c0aab016454580004355-320-0.jpg" alt="">
                        </a>
                    </div>
                    <div class="descricao-produtos">
                        <a href="">
                            <h5>T-SHIRT BICICLETA</h5>
                        </a>
                        <p>R$69,90</p>
                        <p>3X DE R$23,30 SEM JUROS</p>
                    </div>
                </div>

            </div>
        </div>

        <div class="classe-produto">
            <h2>
                Princiais Feminino
            </h2>
            <div class="produtos">
                <div class="produto">
                    <div class="img-produtos">
                        <a href="">
                            <img src="https://cea.vtexassets.com/arquivos/ids/55947102-426-512?width=320&height=320" width="320px" alt="">
                        </a>
                    </div>
                    <div class="descricao-produtos">
                        <a href="">
                            <h5>T-SHIRT BICICLETA</h5>
                        </a>
                        <p>R$69,90</p>
                        <p>3X DE R$23,30 SEM JUROS</p>
                    </div>
                </div>

                <div class="produto">
                    <div class="img-produtos">
                        <a href="">
                            <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/895/331/products/tshirt-silk-telha-frente-014031-abba04dec7e7c0aab016454580004355-320-0.jpg" alt="">
                        </a>
                    </div>
                    <div class="descricao-produtos">
                        <a href="">
                            <h5>T-SHIRT BICICLETA</h5>
                        </a>
                        <p>R$69,90</p>
                        <p>3X DE R$23,30 SEM JUROS</p>
                    </div>
                </div>

                <div class="produto">
                    <div class="img-produtos">
                        <a href="">
                            <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/895/331/products/tshirt-silk-telha-frente-014031-abba04dec7e7c0aab016454580004355-320-0.jpg" alt="">
                        </a>
                    </div>
                    <div class="descricao-produtos">
                        <a href="">
                            <h5>T-SHIRT BICICLETA</h5>
                        </a>
                        <p>R$69,90</p>
                        <p>3X DE R$23,30 SEM JUROS</p>
                    </div>
                </div>
                
                <div class="produto">
                    <div class="img-produtos">
                        <a href="">
                            <img src="https://d3ugyf2ht6aenh.cloudfront.net/stores/895/331/products/tshirt-silk-telha-frente-014031-abba04dec7e7c0aab016454580004355-320-0.jpg" alt="">
                        </a>
                    </div>
                    <div class="descricao-produtos">
                        <a href="">
                            <h5>T-SHIRT BICICLETA</h5>
                        </a>
                        <p>R$69,90</p>
                        <p>3X DE R$23,30 SEM JUROS</p>
                    </div>
                </div>

            </div>
        </div>


    </div>

</div>