<div class="container-login">

    <div class="login">
        <div class="pagina-user">
            <h4 class="atual">
                <a href="/login">
                    Login
                </a>
            </h4>
            <h4>
                <a href="/registrar">
                    Registre-se
                </a>
            </h4>
        </div>
        <form action="/autenticar" method="post">
            <label for="email-login">Email: 
                <input type="email" name="email" id="email-login">
            </label>
            <?php if(isset($_GET['email']) && $_GET['email'] == 'vazio'){ ?>
                <p style="color: red; margin: -5px 0px 10px 0px;">Espaço vazio</p>
            <?php } ?>
            <label for="senha-login">Senha: 
                <input type="password" name="senha" id="senha-login">
            </label>
            <div>
                <input type="checkbox" name="remember" id="remember">lembrar de mim
            </div>
            <input type="submit" value="Entrar">
        </form>
    </div>

</div>