<div class="container-login">

    <div class="login">
        <div class="pagina-user">
            <h4>
                <a href="/login">
                    Login
                </a>
            </h4>
            <h4 class="atual">
                <a href="/registrar">
                    Registre-se
                </a>
            </h4>
        </div>
        <form action="cadastrar" method="post">
            <label for="nome-registrar">Nome: </label>
                <input type="text" name="nome" id="nome-registrar">
            <label for="email-registrar">Email: </label>
                <input type="email" name="email" id="email-registrar">
            <?php if(isset($_GET['email']) && $_GET['email'] == 'existente'){ ?>
                <p style="color: red; margin: -5px 0px 10px 0px;">Email existente</p>
            <?php } ?>
            <label for="senha-registrar">Senha: </label>
                <input type="password" name="senha" id="senha-registrar">
            <label for="confirmar-registrar">Confirmar senha: </label>
                <input type="password" name="confirmar-senha" id="confirmar-registrar">
            <input type="submit" value="Entrar">
        </form>
    </div>

</div>