<div class="container-login">

    <div class="login">
        <div class="pagina-user">
            <h4>
                <a href="/login">
                    Login
                </a>
            </h4>
            <h4 class="atual">
                <a href="/registrar">
                    Registre-se
                </a>
            </h4>
        </div>
        <form action="">
            <label for="nome-registrar">Nome: </label>
                <input type="text" name="nome" id="nome-registrar">
            <label for="email-registrar">Email: </label>
                <input type="email" name="email" id="email-registrar">
            <label for="senha-registrar">Senha: </label>
                <input type="password" name="senha" id="senha-registrar">
            <label for="confirmar-registrar">Confirmar senha: </label>
                <input type="password" name="confirmar-senha" id="confirmar-registrar">
            <label for="remember">
                <input type="checkbox" name="remember" id="remember">
                Lembrar de mim
            </label>
            <input type="submit" value="Entrar">
        </form>
    </div>

</div>